### ISSUE TITLE
Suspicious memory usage

### ISSUE THREAD

**Issue by ethinx** [flomesh-io/pipy#105]
## What happened

Run pipy proxy with script in `sample/http`, client send requests to route `/`, `/api`, `/api/private`, `/hi`, `/home` in http/https randomly. Run several rounds of the test, and I notice that the memory usage of pipy may ramp up at the time of new run starts.

## Reproduce the issue
1. Start pipy with script in `sample/http`, two upstreams, and one http server for responding the pipy logging request
2. Run test by [k6](https://github.com/grafana/k6/releases/tag/v0.39.0) and the attached [test.js.gz](https://github.com/flomesh-io/pipy/files/9256117/test.js.gz) script several times
```
while true; do ./k6 run -d 2m -u 1000 test.js; sleep 180; done
```

## Expect behavior
Should some of the memory be recycled after testing, or should the mem usage be stable?

## Screenshots
![CleanShot 2022-08-04 at 10 10 26@2x](https://user-images.githubusercontent.com/965612/182748075-406c713d-3b16-41e1-90b6-0c1c9637e82b.png)

## Version info
```
Version     : 0.50.0-37
Commit      : 5c115a842c4e98559fd83a6271be2d3ba79ef914
Commit Date : Tue, 26 Jul 2022 19:08:51 +0800
Host        : Linux-5.15.0-1014-azure x86_64
OpenSSL     : OpenSSL 1.1.1q  5 Jul 2022
Builtin GUI : No
Tutorial    : No
```

**Comment by pajama-coder** [comment]
Thanks for the report.

From my test here, it seems to happen only with the TLS path. Could you please skip TLS in your test just to see if that's also true in your environment?

**Comment by pajama-coder** [comment]
Thanks for the report.

From my test here, it seems to happen only with the TLS path. Could you please skip TLS in your test just to see if that's also true in your environment?

**Comment by ethinx** [comment]
I tried another round of test, exclude the TLS urls, the memory usage could keep stable till now.

But at the first few hours, memory still ramp up several times. Not confident, I'm trying reproducing it, if possible.

Will be back if there is any further update.

**Comment by ethinx** [comment]
Comes after two days test, with HTTP url, the usage change slightly.

btw, i started 4 pipy instances with `--reuse-port` each time, hope this is irrelevant.

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/965612/183324034-34a09daa-eae0-4cf7-b65b-1f50adecaca7.png">

**Comment by pajama-coder** [comment]
This issue was found in a very old version. Since it hasn't been seen in other versions later on, I'll close it for now.
