### ISSUE TITLE
Pipy process crashes when printing "__inbound.remoteAddress" in onEnd()

### ISSUE THREAD

**Issue by wanpf** [flomesh-io/pipy#112]
Pipy process crashes when printing "__inbound.remoteAddress" in onEnd().

Version     : nightly-202208231036
Commit      : 8436d3bcd9c1b05f4fd6bea5111cedf3db098ec4
Commit Date : Mon, 22 Aug 2022 23:05:38 +0800
Host        : Linux-5.15.0-43-generic x86_64
OpenSSL     : OpenSSL 1.1.1q  5 Jul 2022
Builtin GUI : Yes
Samples     : Yes

test pjs:
///////////////

((
) => pipy({
})
  .listen(8081)
  .onEnd(
    () => console.log('bug ......', __inbound.remoteAddress)
  )
  .serveHTTP(
    () => new Message('Hi, there!\n')
  )
)()

**Comment by pajama-coder** [comment]
Solved in b80b1bc464f95b3ad6c2f2b38c2e7c0acc065877.
@wanpf Please give it a check to see if it works. Thanks.

**Comment by wanpf** [comment]
Tested and the problem has been fixed.
