### ISSUE TITLE
Allow listening on Virtual IPs

### ISSUE THREAD

**Issue by naqvis** [flomesh-io/pipy#114]
## Feature Request

- Is your feature request related to a problem? Please describe clearly and concisely what is it.

   For some use cases, there is a need to have Pipy listens on Virtual IP(s) and ports.
- Describe the feature you would like, optionally illustrated by examples, and how it will solve the above problem.

Would like to have Pipy support listening on Virtual IP Addresses, so that one can have the ability to start Pipy instance(s) on Virtual IPs and ports like:

```js
.listen('vip1:port')
.listen('vip2:port')
.....
```
- Describe considered alternative solutions, and the reasons why you have not proposed them as a solution here.

    Current approach is to listen on specific IP or address bind to specific NIC.

- Does it break backward compatibility, if yes then what's the migration path?
  No

**Comment by pajama-coder** [comment]
This wasn't possible because Pipy sees vip1:port and vip2:port as the same listener since the port is the same. Only one listener is created in the end.

I've changed that in 83083cf054b55eb51a93d20adb43402eb96e2797 and this usage should be supported now.
