### ISSUE TITLE
Can not access admin port with container

### ISSUE THREAD

**Issue by liangyuanpeng** [flomesh-io/pipy#145]
# Reproduce steps

```shell
git clone git@github.com:flomesh-io/pipy.git
cd pipy
docker run --rm --name pipy -v $PWD/tutorial:/tutorial -p 6060:6060 flomesh/pipy:0.90.0-18  pipy --admin-port=6060 tutorial/02-echo/hello.js
```

# Other

And then access IP:6060, it's not working for me. also tryed args of `--admin-port=:6060`  and  `--admin-port=192.168.3.87:6060` .

## Pipy Logs

```
...
2023-03-09 05:50:49.131 [INF] [listener] Listening on TCP port 8080 at 0.0.0.0
2023-03-09 05:50:49.131 [INF] [listener] Listening on TCP port 8081 at 0.0.0.0
2023-03-09 05:50:49.131 [INF] [listener] Listening on TCP port 8082 at 0.0.0.0
2023-03-09 05:50:49.131 [INF] [start] Thread 0 started
2023-03-09 05:50:49.131 [INF] [admin] Starting admin service...
2023-03-09 05:50:49.132 [INF] [listener] Listening on TCP port 6060 at ::
```

Remind me if i missed something,Thanks.

**Comment by ethinx** [comment]
@liangyuanpeng The command you tried appears to be correct, and port 6060 is open and accessible. However, if you are hoping to access the GUI, the image `flomesh/pipy` does not have a GUI built-in. I would recommend trying `flomesh/pipy-repo` instead. Here's the modified command:

```
docker run --rm --name pipy -p 6060:6060 flomesh/pipy-repo:0.90.0-18 pipy --admin-port=6060
```

BTW, if you only want to test the built-in samples, there is no need to mount a local path into the container. The tutorials and samples are already integrated into the GUI by default.

**Comment by liangyuanpeng** [comment]
> 如果您希望访问 GUI，则图像flomesh/pipy没有内置 GUI

That is what i want, I change image to `flomesh/pipy-repo` and it's working for me, Thanks.
