### ISSUE TITLE
where is benchmark 

### ISSUE THREAD

**Issue by ghtian123** [flomesh-io/pipy#172]
## Discussion

- What aspect of Pipy would you like to see improved?
- What are the reasons?
- Include practical examples to illustrate your points.
- Optionally add one (or more) proposals to improve the current situation.

**Comment by caishu97** [comment]
there are some benchmark we did and recorded in wiki page : https://github.com/flomesh-io/pipy/wiki

**Comment by ghtian123** [comment]
There is some help, but I would like to know the performance comparison chart with envoy, especially on machines with poor performance.

**Comment by ghtian123** [comment]
On machines with poor performance, we want to use pipy instead of envoy

**Comment by caishu97** [comment]
> On machines with poor performance, we want to use pipy instead of envoy

Yes, you can replace envoy with pipy. And if there is any issue or need help, you can contact us in WeChat group and slack.

**Comment by caishu97** [comment]
> There is some help, but I would like to know the performance comparison chart with envoy, especially on machines with poor performance.

We do did a lot performance test against pipy and envoy,  you can reference this one : https://mp.weixin.qq.com/s/pzK3qjvlAr-0EuXP8w1oAw . It's post on our '公众号'.  See if this is what you are looking for.  Pipy is about 30% faster than envoy and about 50% resource less than envoy in most test cases.
