### ISSUE TITLE
ECONNREFUSED: version 1.5.3 macos admin gui

### ISSUE THREAD

**Issue by victor-develop** [flomesh-io/pipy#198]
## Bug Report

release: [pipy-1.5.3-macos-aarch64.tar.gz](https://github.com/flomesh-io/pipy/releases/download/1.5.3/pipy-1.5.3-macos-aarch64.tar.gz)

```
./pipy
```

result: ECONNREFUSED

**Comment by ethinx** [comment]
Hi @victor-develop

Could you elaborate on your problem?

I think you want to access the admin UI, current binary release doesn't enable builtin UI. If you want a try, you could use the docker image `flomesh/pipy-repo:1.5.3`

```
# docker run -p 6060:6060 flomesh/pipy-repo:1.5.3 pipy
2024-11-08 03:02:30.106 [INF] [admin] Starting admin service...
2024-11-08 03:02:30.107 [INF] [listener] Listening on TCP port 6060 at ::

=============================================

  You can now view Pipy GUI in the browser:

    http://localhost:6060/

=============================================
```

**Comment by victor-develop** [comment]
Thanks for clarification.
