### ISSUE TITLE
Compile Pipy GUI issue

### ISSUE THREAD

**Issue by Luck0o0** [flomesh-io/pipy#20]
When I build pipy gui, I got this problem,  how to resolve this ?
![issue](https://user-images.githubusercontent.com/4303729/122502624-8a739800-d029-11eb-8ef3-a300225667f5.png)

**Comment by caishu97** [comment]
It works for me by using npm mirror: 

npm install -g cnpm --registry=https://registry.npm.taobao.org
cd gui
cnpm install 
cnpm run build
cd ../
./build.sh
