### ISSUE TITLE
error when running build.sh

### ISSUE THREAD

**Issue by zengyuxing007** [flomesh-io/pipy#23]
root@service-mesh-011122063081:~/openSource/pipy# ./build.sh
error: unknown option `show-current'
usage: git branch [<options>] [-r | -a] [--merged | --no-merged]
   or: git branch [<options>] [-l] [-f] <branch-name> [<start-point>]
   or: git branch [<options>] [-r] (-d | -D) <branch-name>...
   or: git branch [<options>] (-m | -M) [<old-branch>] <new-branch>
   or: git branch [<options>] (-c | -C) [<old-branch>] <new-branch>
   or: git branch [<options>] [-r | -a] [--points-at]
   or: git branch [<options>] [-r | -a] [--format]

**Comment by khas-flomesh** [comment]
Thank you for your contribution!
Yeah, this is caused by git 1.x. It was neglected because we use git 2.x by default.
I'll merge this PR.
Regards
