### ISSUE TITLE
请问支持国密证书吗

### ISSUE THREAD

**Issue by chungang-li** [flomesh-io/pipy#60]

**Comment by caishu97** [comment]
如果说这里“支持国密证书”，是指：
1. 支持国密的TLS，比如国密的HTTPS
2. 支持国密的内容加解密
3. 支持国密的签名与验签

那么目前pipy支持#2和#3，#1的支持还在开发中。目前我们支持某个第三方国密库的TLS，这部分也是这个第三方实现的，我们支持集成到了Pipy中。因此，如果你需要一个开源基于openssl的国密TLS，那么还需要等待一些时间；如果你可以考虑付费的产品，我们可以推荐这个第三方国密团队的产品。
